import { Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = (props) => {
  console.log(props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Monogatari Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Text fontSize="4xl" as="h1" fontWeight="bold">
          Monogatari Quotes
        </Text>
      </main>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const res = await fetch("http:/localhost:4000/quotes");
  const data = await res.json();
  return {
    props: {
      quote: data.content,
    },
  };
}
